# Generated by Django 3.2.8 on 2021-10-28 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='key',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
