# Generated by Django 3.2.8 on 2021-11-03 03:56

import django.core.validators
from django.db import migrations, models
import msgserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgserver', '0002_alter_message_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='key',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8), msgserver.models.validatealnum, msgserver.models.validatekeydupe]),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=160, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
